<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vprybeha-w7" ignored="0" tests="1" failures="1" timestamp="03 Jan 2019 15:28:44 GMT" time="19.993" errors="0">
  <testcase name="firsttest" time="10.838" classname="TestClass">
    <failure type="SupportClasses.NewAssertError" message="Assertion error with message: expected [2] but found [1]">
      <![CDATA[SupportClasses.NewAssertError: Assertion error with message: expected [2] but found [1]
at TestClass.firsttest(TestClass.java:32)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- firsttest -->
</testsuite>
