<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1548771751367" stop="1548771762764" version="1.5.4" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Sone tests : Investments</name>
    <title>Sone tests : Investments</title>
    <test-cases>
        <test-case start="1548771757883" stop="1548771760565" status="failed">
            <name>Investment_ACH</name>
            <title>Test Individual US investment process for ACH method</title>
            <description type="text">Login &gt; check account type &gt; make ACH investment</description>
            <failure>
                <message>AssertionError: expected [2] but found [1]</message>
                <stack-trace>java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at UnitClassSet.Investment.test_IndividualUS.Investment_ACH(test_IndividualUS.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Sone tests"/>
                <label name="testGroup" value="Investments"/>
                <label name="testClass" value="UnitClassSet.Investment.test_IndividualUS"/>
                <label name="testMethod" value="Investment_ACH"/>
                <label name="severity" value="critical"/>
                <label name="feature" value="Investment"/>
                <label name="feature" value="Individual US"/>
                <label name="feature" value="ACH"/>
                <label name="host" value="vprybeha-w7"/>
                <label name="thread" value="4312@vprybeha-w7.TestNG-test=Investments-1(14)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
